### ISSUE TITLE
Save playlist when playlists directort doesn't exist

### ISSUE THREAD

**Issue by retroaalto** [jooapa/jammer#31]
if $HOME/jammer/playlists doesn't exist program core dumps when saving a new playlst

```
│ Save as playlist                                                                                                          
│ │ Enter playlist name: asdf                                                                                             
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/ilako/jammer/playlists/asdf.jammer'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException) 
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException) 
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)   
   at System.IO.File.WriteAllLines(String path, IEnumerable`1 contents, Encoding encoding)
   at jammer.Playlists.Save(String playlistName, Boolean force)  
   at TUI.SaveAsPlaylist()                                
   at jammer.Start.CheckKeyboard()          
   at jammer.Start.Loop()                                                                                                   
```

**Comment by retroaalto** [comment]
When saving a playlist check the directory exists. If not, create.
