### ISSUE TITLE
Code dumped if playlist file is empty

### ISSUE THREAD

**Issue by retroaalto** [jooapa/jammer#34]
```
$ cat asdf.jammer
$ jammer -p asdf
Launching Jammer...
Starting up asdf.jammer
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at jammer.Playlists.Play(String playlist, Boolean fromCli)
   at jammer.Start.Run(String[] args)
   at Program.Main(String[] args)
zsh: IOT instruction (core dumped)  jammer -p asdf
```

**Comment by jooapa** [comment]
done so
